name: Update Latest dev.to Posts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # runs daily at UTC 06:00

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Update README with dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/roshanacharya"
          max_post_count: 5
